import type { SiteData } from "@/lib/types";

export const siteData: SiteData = {
  name: "Ahmed Messaad",
  title: "PhD Researcher & AI/ML Engineer",
  description: "Ahmed Messaad — PhD Researcher and AI/ML Engineer working across applied deep learning, medical AI, and intelligent systems.",
  hero: {
    eyebrow: "PhD Researcher · AI/ML Engineer",
    headline: ["I build the model.", "Then I build", "the product."],
    lead: "Research-driven deep learning for clinical and diagnostic applications. I explore medical imaging, sequential decision-making, and health data — then build the systems that bring intelligent models into practice.",
    primaryLabel: "Explore research",
    primaryHref: "#work",
    cvLabel: "Download CV",
    cvHref: "/resume.pdf"
  },
  stats: [
    { value: "99%", label: "Brain tumor accuracy" },
    { value: "BBC", label: "4Tech featured" },
    { value: "3", label: "Apps in production" }
  ],
  marquee: ["Medical AI", "Computer Vision", "Reinforcement Learning", "Full-Stack Products", "DICOM Pipelines", "Research to Deployment"],
  work: {
    label: "Research & engineering",
    heading: ["From research", "to real-world systems."],
    note: "A selection of applied research and engineering projects across clinical AI, computer vision, reinforcement learning, and full-stack systems. Reported metrics describe project evaluations, not clinical outcomes.",
    featured: {
      eyebrow: "Featured · Medical computer vision · BBC 4Tech",
      name: "HemaVision",
      description: "Automated hematology platform replacing manual microscopy for routine blood analysis. YOLOv8 detection, U-Net segmentation, and a disease layer flagging cell morphology tied to leukemia, malaria, and anemia. Validated by a clinical hematologist before being featured on BBC News Arabic's 4Tech program.",
      chips: ["YOLOv8", "U-Net", "OpenCV", "PyTorch", "97% accuracy", "45 min → 3 min"],
      linkLabel: "Watch BBC coverage",
      href: "https://www.youtube.com/watch?v=fX77vZlHkng",
      pipeline: [
        { num: "01 · INPUT", title: "Detection", description: "YOLOv8 locates cells in dense smear images" },
        { num: "02 · PROCESS", title: "Segmentation", description: "U-Net isolates overlapping cell regions" },
        { num: "03 · OUTPUT", title: "Classification", description: "RBC / WBC subtypes + disease flags" }
      ],
      pipelineFoot: ["Computer vision pipeline", "Clinician-validated"]
    },
    projects: [
      {
        number: "01", kind: "Medical computer vision", name: "AIRM — Brain MRI Classification",
        description: "EfficientNet-B7 reaching 99% across four tumor categories with a full DICOM pipeline and a radiologist-validated PyQt5 interface built for real clinical workflow integration.",
        resultLabel: "Result", result: "99% four-class accuracy. DICOM pipeline tested with hospital MRI scanners.",
        stack: ["EfficientNet-B7", "PyDICOM", "PyQt5"], linkLabel: "Watch demo ↗", href: "https://youtu.be/2OeqBKF3X_A"
      },
      {
        number: "02", kind: "Reinforcement learning · Healthcare", name: "Medical Treatment DRL",
        description: "ICU treatment timing agent on MIMIC-III. A2C reached 99.5% clinical appropriateness with +76–145 reward improvement. Rule-based safety filter lifted PPO/DQN appropriateness by 40 points.",
        resultLabel: "Result", result: "99.5% appropriateness. 26-dimensional Gym environment modeling temporal lab trends.",
        stack: ["Stable-Baselines3", "MIMIC-III", "Gym"], linkLabel: "View code ↗", href: "https://github.com/RYANX9/medical-treatment-drl/"
      },
      {
        number: "03", kind: "Full-stack product", name: "SpecMob",
        description: "Phone comparison and discovery platform. Next.js + FastAPI + async Postgres, trigram typo-tolerant search, tiered caching. Product copy generated by Gemini with a deterministic fallback — AI layer never blocks rendering.",
        resultLabel: "Live product", result: "Full-stack from nothing to production: frontend, API, database, AI copy layer.",
        stack: ["Next.js", "FastAPI", "PostgreSQL", "Gemini"], linkLabel: "Visit site ↗", href: "https://specmob.vercel.app"
      },
      {
        number: "04", kind: "Applied ML · Research thesis", name: "My Daily Health",
        description: "Multi-disease diagnostic platform across five domains. Systematic evaluation of 12 architectures with stratified cross-validation. Secure clinical workflow, sub-200ms inference. ICSTEM 2023 Outstanding Presentation Award.",
        resultLabel: "Result", result: "90–99% accuracy across five disease domains on M.Sc. thesis evaluation.",
        stack: ["TensorFlow", "PyTorch", "Flask", "ResNet"], linkLabel: "Watch demo ↗", href: "https://youtu.be/kh7WBjNPpEM"
      }
    ],
    more: [
      { number: "05", name: "Healthcare Cost Prediction", kind: "Conv1D · SHAP · R² 0.88", linkLabel: "View ↗", href: "https://github.com/RYANX9/healthcare-cost-prediction" },
      { number: "06", name: "Deep RL for Crypto Trading", kind: "PPO · A2C · Negative result", linkLabel: "View ↗", href: "https://github.com/RYANX9/deep-rl-trading" },
      { number: "07", name: "Day Tracker", kind: "Next.js · PostgreSQL · Web Push", linkLabel: "View ↗", href: "https://github.com/RYANX9/rystudio" },
      { number: "08", name: "Git-Backed CMS", kind: "Next.js · GitHub Contents API", linkLabel: "Visit ↗", href: "https://zaid-saad.vercel.app" }
    ]
  },
  publications: {
    label: "Publications",
    heading: ["Research, in", "the literature."],
    note: "Conference research and scientific contributions.",
    entries: [
      {
        status: "Conference presentation · December 2023",
        title: "Helping System for Brain Disease Diagnosis Using Deep Learning",
        description: "Presented at the International Conference on Science, Technology, Engineering and Management (ICSTEM), Istanbul, Turkey, 3–7 December 2023.",
        tags: ["Transfer Learning", "Deep Learning", "Medical Imaging"],
        award: "Best Presentation Award",
        linkLabel: "View certificate",
        href: "/Ahmed_ISER_certificate.pdf",
        note: "ICSTEM 2023"
      }
    ]
  },
  about: {
    label: "About",
    statement: "Research makes me careful about what a model actually knows. Systems work makes me care about latency, failure modes, and what happens when the happy path breaks.",
    paragraphs: [
      "I am a PhD researcher and AI/ML engineer working across applied deep learning, clinical and diagnostic applications, and the engineering needed to turn research into usable systems. Research and implementation inform each other.",
      "My project work includes brain tumor classification, automated blood cell detection, and ICU treatment-timing agents. I care about the assumptions behind a result, how it is evaluated, and what it takes to make a system useful beyond an experiment.",
      "On the systems side: Next.js and React on the frontend, FastAPI or Flask on the backend, Postgres for storage. I've taken a full product from nothing to production and keep several Postgres-backed apps running."
    ],
    facts: [
      { label: "Core focus", value: "Medical AI · Applied systems" },
      { label: "Technical range", value: "CV · DL · RL · Web" },
      { label: "Academic path", value: "PhD Researcher · M.Sc. Embedded Systems" },
      { label: "Based in", value: "Algeria" }
    ]
  },
  contact: {
    label: "Contact",
    heading: "Open to research collaborations and ML engineering roles.",
    description: "Reach out if you're working in medical AI, need an applied ML engineer, or need someone who can take a model all the way to a shipped product.",
    buttonLabel: "Email me ↗",
    email: "ahmed.messaad@outlook.com"
  },
  footer: {
    copyrightName: "Ahmed Messaad",
    links: [
      { label: "GitHub ↗", href: "https://github.com/RYANX9" },
      { label: "LinkedIn ↗", href: "https://linkedin.com/in/ahmedmessaad" },
      { label: "Kaggle ↗", href: "https://kaggle.com/ahmedmessaad" },
      { label: "Email ↗", href: "mailto:ahmed.messaad@outlook.com" }
    ]
  }
};

